version: "3"

services:
  notebooker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      # config variables are defined in notebooker/web/config/setting.py
      PORT: 11828
      LOGGING_LEVEL: info
      MONGO_USER: root
      MONGO_PASSWORD: toor
      MONGO_HOST: mongodb:27017
      DATABASE_NAME: admin
      RESULT_COLLECTION_NAME: NOTEBOOK_OUTPUT
      PY_TEMPLATE_BASE_DIR: /var/run/template_repo
    volumes:
      - git-repo:/var/run/template_repo
    command: ["notebooker-cli", "--mongo-host", "${MONGO_HOST}", "--mongo-user", "${MONGO_USER}", "--mongo-password", "${MONGO_USER}", "start-webapp", "--port", "${PORT}"]
    ports:
      - "8080:11828"
    depends_on:
      - mongodb
    restart: always

  # populate the volume where the git-repo resides with the example
  git-repo-init:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - git-repo:/var/run/template_repo
    entrypoint: ["/bin/sh", "-c"]
    user: root
    command:
      - |
        set -o errexit -o nounset -o pipefail
        # needed for the git init
        git config --global user.email "example@example.com"
        git config --global user.name "Example Name"
        cd /var/run/template_repo
        cp -R /opt/conda/lib/python3.8/site-packages/notebooker/notebook_templates_example/ ./
        git init .
        git add .
        git commit -m "Initial commit"

  mongodb:
    image: mongo:4.4.1-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor

volumes:
  git-repo:
